name: AWS OIDC Connect Demo
on:
  push
env:
  AWS_REGION: "us-east-1"
permissions:
  id-token: write    # OIDC token request permission
  contents: read     # Required for actions/checkout
jobs:
  DemoOIDC:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::058264394137:role/oidc-deepak-kumar    # Your IAM role ARN from GitHub Secrets
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Print assumed role
        run: aws sts get-caller-identity
